sentry:
  dsn: "{SENTRY_DSN}"
  release:
    name: "{SENTRY_RELEASE_NAME}"
# This one is optional ... only if you want to use ai-story command
openAi:
  token: ...
amqp:
  url: "{AMQP_URL}"
discord:
  token: "MTAxMjgxMTkwOTM4NjQ4MTc2NA.Gzhs-o.qHogYLEVMY9ihOmT0Ig1uZWsp0RYyqdKJz50uE"
deploy:
  port: "{PORT}"
mongo:
  uri: "${MONGO_URI}"
wombo-dream:
  api:
    url: "https://paint.api.wombo.ai/api"
  googleAuthUrl: "https://www.googleapis.com/identitytoolkit/v3/relyingparty/signupNewUser?key=AIzaSyDCvp5MTJLUdtBYEKYWXJrlLzu1zuKM6Xw"
